batch_size: 64
fft_length: 384
frame_length: 256
frame_step: 160
input_shape:
- 1392
- 193
learning_rate: 0.0005
max_spectrogram_length: 1392
max_text_length: 186
model_path: Models/05_sound_to_text\202305031703
train_epochs: 10
train_workers: 12
vocab: 'abcdefghijklmnopqrstuvwxyz''?! '
